# Houseflow hub configuration

[hub]
id = "2adc257a-394c-49bd-ae97-4c5a98b49d84"

[network]
address = "0.0.0.0"
port = 1234

[[accessories]]
id = "37c6a8bd-264c-4653-a641-c9b574207be5"
name = "Thermometer"
room-name = "Bedroom"
manufacturer = "xiaomi-mijia"
model = "hygro-thermometer"
mac-address = "A4:C1:38:EF:77:51"

[controllers.meta]
[controllers.hap]
pin = "12345678"
name = "Awesome Hub"

[controllers.lighthouse]
url = "http://lighthouse"
password = "hard-password"


[providers.mijia]
[providers.hive]