[package]
name = "houseflow-server"
version = "0.1.2"
description = "Server for Houseflow"
homepage = "https://github.com/gbaranski/houseflow"
repository = "https://github.com/gbaranski/houseflow"
authors = ["Grzegorz Baranski <root@gbaranski.com>"]
license = "GPL-3.0-or-later"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
houseflow-db = { path="../db", version="0.1.1", features = ["sqlite"] }
houseflow-types = { path="../types", version="0.1.1", features=[
    "actix",
    "token",
    "auth",
    "fulfillment",
    "lighthouse",
    "admin",
] }
houseflow-config = { path="../config", version="0.1.1", features=["server", "fs"] }

actix = "0.12.0"
actix-rt = "2.2.0"
actix-web = { version = "4.0.0-beta.8", features = ["rustls"]}
actix-web-actors = "4.0.0-beta.6"
actix-service = "2.0.0"
rustls = "0.19.1"

tokio = { version="1.5", features=["sync"] }

validator = "0.13.0"
thiserror = "1.0"

itertools = "0.10"

bytes = "1.0"
serde = "1.0"
serde_json = "1.0"
rust-argon2 = "0.8.3"
semver = "1.0.3"
rand = "0.8.4"
async-trait = "0.1.50"
futures = "0.3.15"
url = { version = "2.2.2", features = ["serde"] }
chrono = "0.4.19"
sled = "0.34.6"
tracing = "0.1.26"

tracing-actix-web = "0.4.0-beta.9"
