# Houseflow device configuration

# [server]
# hostname = # Hostname of the server, e.g `localhost` 
# use-tls =  # Whether to use TLS.

# [garage]
# [garage.credentials]
# device-id = # Unique 16 byte hex-encoded device identifier.
# device-password = # Variable length password

# [gate]
# [gate.credentials]
# device-id = # Unique 16 byte hex-encoded device identifier.
# device-password = # Variable length password

# [light]
# [light.credentials]
# device-id = # Unique 16 byte hex-encoded device identifier.
# device-password = # Variable length password

