# Houseflow device configuration

device-type = "garage"

[server]
hostname = "example.com"   # Hostname of the server, e.g `localhost` 
use-tls = true         # Whether to use TLS.

[credentials]
id = "546c8a4b71f04c78bd338069ad3b174b"
password = "garage-password"

[traits.open-close]
command = "echo 1"
