# Houseflow server configuration
# Some values like secrets were randomly generated, just to save you some time generating them

# Change to 0.0.0.0 to allow clients from outside network to connect
# hostname: {}

secrets:
  refresh_key: {}
  access_key: {}
  authorization_code_key: {}

# Optional. Uncomment and adjust to enable TLS support
# tls:
#  certificate_path: /etc/letsencrypt/live/example.com/fullchain.pem
#  private_key_path: /etc/letsencrypt/live/example.com/privkey.pem

# Optional. Uncomment and adjust to enable Google Home support
# google:
#   # Must match with ClientID & Client Secret in Actions console -> Account Linking
#   client_id: {}
#   client_secret: {}
#   
#   # ProjectID used when creating project on Google Cloud
#   project_id: your-project-id
