[network]
address = "0.0.0.0"
port = 1234
base-url = "http://localhost:1234"

[secrets]
refresh-key = "${REFRESH_KEY}"
access-key = "${ACCESS_KEY}"
authorization-code-key = "${AUTHORIZATION_CODE_KEY}"

[tls]
certificate = "/etc/certificate"
private-key = "/etc/private-key"
address = "1.2.3.4"
port = 4321

[mailers.smtp]
url = "smtp://${EMAIL_USERNAME}:${EMAIL_PASSWORD}@email.houseflow.gbaranski.com:666"
from = "houseflow@gbaranski.com"

[mailers.dummy]

[controllers.meta]

[providers.lighthouse]
[[providers.lighthouse.hubs]]
id = "c3b846ed-74f1-4fd9-90d2-e6c2669dfaa6"
name = "Simple Hub"
password-hash = "some-password-hash"
structure-id = "bd7feab5033940e296ed7fcdc700ba65"

[logins.google]
client-id = "google-login-client-id"

[[structures]]
id = "bd7feab5033940e296ed7fcdc700ba65"
name = "Zukago"

[[users]]
id = "861ccceaa3e349138ce2498768dbfe09"
username = "gbaranski"
email = "root@gbaranski.com"
admin = false

[[permissions]]
structure-id = "bd7feab5033940e296ed7fcdc700ba65"
user-id = "861ccceaa3e349138ce2498768dbfe09"
is-manager = true
